"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FEAUTURE_NAME_METADATA = 'NESTJSX_FEAUTURE_NAME_METADATA';
exports.ACTION_NAME_METADATA = 'NESTJSX_ACTION_NAME_METADATA';
exports.OVERRIDE_METHOD_METADATA = 'NESTJSX_OVERRIDE_METHOD_METADATA';
exports.PARSED_BODY_METADATA = 'NESTJSX_PARSED_BODY_METADATA';
exports.PARSED_CRUD_REQUEST_KEY = 'NESTJSX_PARSED_CRUD_REQUEST_KEY';
exports.CRUD_OPTIONS_METADATA = 'NESTJSX_CRUD_OPTIONS_METADATA';
//# sourceMappingURL=constants.js.map