export declare const FEAUTURE_NAME_METADATA = "NESTJSX_FEAUTURE_NAME_METADATA";
export declare const ACTION_NAME_METADATA = "NESTJSX_ACTION_NAME_METADATA";
export declare const OVERRIDE_METHOD_METADATA = "NESTJSX_OVERRIDE_METHOD_METADATA";
export declare const PARSED_BODY_METADATA = "NESTJSX_PARSED_BODY_METADATA";
export declare const PARSED_CRUD_REQUEST_KEY = "NESTJSX_PARSED_CRUD_REQUEST_KEY";
export declare const CRUD_OPTIONS_METADATA = "NESTJSX_CRUD_OPTIONS_METADATA";
