export declare const OVERRIDE_METHOD_METADATA = "NESTJSX_OVERRIDE_METHOD_METADATA";
export declare const PARSED_CRUD_REQUEST_KEY = "NESTJSX_PARSED_CRUD_REQUEST_KEY";
export declare const CRUD_OPTIONS_METADATA = "NESTJSX_CRUD_OPTIONS_METADATA";
