export const FEAUTURE_NAME_METADATA = 'NESTJSX_FEAUTURE_NAME_METADATA';
export const ACTION_NAME_METADATA = 'NESTJSX_ACTION_NAME_METADATA';
export const BASE_PATH_METADATA = 'NESTJSX_BASE_PATH_METADATA';
export const BASE_METHOD_METADATA = 'NESTJSX_BASE_METHOD_METADATA';
export const OVERRIDE_METHOD_METADATA = 'NESTJSX_OVERRIDE_METHOD_METADATA';
